### ISSUE TITLE
Pilot Focus III isp bonus has stopped working correctly completely

### ISSUE THREAD

**Issue by smjjames** [jrossignol/Strategia#23] opened 2016-02-15 18:04 UTC
Branchoff of issue 22, detailed in forum post: http://forum.kerbalspaceprogram.com/index.php?/topic/131808-105-strategia-v100-2016-02-10/&page=2#comment-2410404 Output log is also there.

**Comment by jrossignol** [comment] 2016-02-27 04:45
Still haven't dug into this at all, although @KSPSnark made a change in Better Burn Time related to this:
https://github.com/KSPSnark/BetterBurnTime/commit/f9068fa5a671e334164d0a6911b67587a41a7192

Which may mean that my issue is I need to force call an update function so that ModuleEngines.realISP (and possibly other fields) get updated.

**Comment by smjjames** [comment] 2016-02-27 15:19
Yeah, that was him responding to the fact that I said that it was screwed up with strategia (in much nicer words of course) and that was his attempt to fix.

**Comment by KSPSnark** [comment] 2016-02-28 03:26
What BetterBurnTime does is use the engine's Isp for doing burn-time predictions.  The issue is, where to get that value from.  Until my recent change, it always used ModuleEngines.realIsp.  Then @smjjames mentioned that it was giving wrong values when used with Strategia.  I had no idea why, but looked at the Strategia code to see what you're doing, and saw that you're altering the atmosphereCurve for pressure=0.  So in an attempt to deal with that, I switched BBT to use the atmosphere-curve value.

If you do end up switching Strategia to directly edit ModuleEngines.realIsp, then perhaps I should go switch BetterBurnTime back to the way it was?

**Comment by jrossignol** [comment] 2016-03-02 05:02
Still having trouble reproducing this issue, but I do have it for evaluating the realISP field now - so I can say for sure that will always have the correct value when I release the next update.

**Comment by jrossignol** [comment] 2016-03-02 21:48
Think this is now fixed, will revisit if not.

@KSPSnark - There should be nothing stopping you from moving back to the realISP field.

**Closed by jrossignol** 2016-03-02 21:48 UTC
Labels: bug
